# Generated by Django 6.0.6 on 2026-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Student_ID", models.IntegerField(max_length=20, unique=True)),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Age", models.IntegerField()),
                ("Department", models.CharField(max_length=100)),
            ],
        ),
    ]
