# Generated by Django 6.0.6 on 2026-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Age", models.IntegerField()),
                ("course", models.CharField(max_length=100)),
                ("batch", models.IntegerField()),
                ("department", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("re_password", models.CharField(max_length=100)),
                ("textarea", models.TextField()),
                ("payment", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
